import { currentDatetimeString } from '@atproto/lex';
import { Client } from '@atproto/lex-client';
import { PasswordSession } from '@atproto/lex-password-session';
import { CronJob } from 'cron';
import * as dotenv from 'dotenv';

// Generated by `lex build` from the lexicons in ./lexicons (see package.json).
import { app } from './src/lexicons/index.js';

dotenv.config();

async function main() {
    // Log in with an App Password. `PasswordSession` handles session creation
    // and refresh; pass it to a `Client` to make authenticated requests.
    const session = await PasswordSession.login({
        service: 'https://bsky.social',
        identifier: process.env.BLUESKY_USERNAME!,
        password: process.env.BLUESKY_PASSWORD!,
    });
    const client = new Client(session);

    // Create an `app.bsky.feed.post` record. The record shape is fully typed
    // from the generated lexicon, so `text`/`createdAt` are checked at compile time.
    await client.create(app.bsky.feed.post, {
        text: '🙂',
        createdAt: currentDatetimeString(),
    });
    console.log('Just posted!');
}

main();

// Run this on a cron job
const scheduleExpressionMinute = '* * * * *'; // Run once every minute for testing
const scheduleExpression = '0 */3 * * *'; // Run once every three hours in prod

const job = new CronJob(scheduleExpression, main); // change to scheduleExpressionMinute for testing

job.start();
