// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config')

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname)

// Allows accessing /assets/oauth-client-metadata.json when running "expo start --web"
config.resolver.assetExts.push('json')

// The lexicons generated by `lex build` in src/lexicons/ are TypeScript ESM
// that imports sibling modules with explicit ".js" specifiers (e.g.
// `export * as app from './app.js'`). Metro's resolver does not map a ".js"
// specifier to the corresponding ".ts" source, so resolve the literal path
// first (real .js files keep working) and fall back to the extensionless form,
// letting Metro find the ".ts" file.
const defaultResolveRequest = config.resolver.resolveRequest
config.resolver.resolveRequest = (context, moduleName, platform) => {
  const resolve = defaultResolveRequest ?? context.resolveRequest
  if (/^\.{1,2}\//.test(moduleName) && moduleName.endsWith('.js')) {
    try {
      return resolve(context, moduleName, platform)
    } catch {
      return resolve(context, moduleName.slice(0, -'.js'.length), platform)
    }
  }
  return resolve(context, moduleName, platform)
}

module.exports = config
